#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MS 업무자동화 컨설팅 CLI 에이전트 - 사용자 매뉴얼 생성
Generated by gen-manual skill
"""

from docx import Document
from docx.shared import Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import datetime
import os

# ════════════════════════════════════════════════════════════
# [DATA 섹션] — 프로그램 정보
# ════════════════════════════════════════════════════════════

APP_NAME        = "MS 업무자동화 컨설팅 CLI 에이전트"
VERSION         = "v2.0"
TARGET_AUDIENCE = "일반 사용자"
TODAY           = datetime.date.today().strftime("%Y-%m-%d")
OUTPUT_PATH     = os.path.join(os.path.dirname(__file__), "20260316_MS업무자동화컨설팅_매뉴얼.docx")

LANG = "ko"

I18N = {
    "ko": {
        "subtitle":         "사용자 매뉴얼",
        "cover_version":    "버전",
        "cover_date":       "작성일",
        "cover_audience":   "대상",
        "toc_title":        "목  차",
        "sec_overview":     "개요",
        "sec_prerequisites":"사전 준비사항",
        "sec_getting_started":"시작하기",
        "sec_features":     "주요 기능",
        "sec_data_storage": "데이터 저장 방식",
        "sec_cautions":     "주의사항 및 제한사항",
        "sec_faq":          "문제 해결 (FAQ)",
        "warning_prefix":   "주의",
        "manual_suffix":    "매뉴얼",
    },
}

def t(key):
    return I18N.get(LANG, I18N["ko"]).get(key, key)

OVERVIEW_TEXT = (
    "Microsoft 생태계(Excel, Word, Teams, Power Automate 등)를 활용한 업무 자동화 솔루션을 분석·제안합니다. "
    "자유형 요구사항을 구조화하고, AI 3종(Claude, Codex, Gemini)의 의견을 비교한 뒤, "
    "즉시 활용 가능한 Power Automate 플로우 설계와 Excel 보고서를 자동 생성합니다."
)

OVERVIEW_SPECS = [
    ("프로그램 타입",    "CLI(Command Line Interface) 에이전트"),
    ("지원 환경",        "Claude Code (Anthropic 공식 IDE)"),
    ("주 대상",          "Microsoft 365 사용자, IT 운영팀, RPA 담당자"),
    ("출력 형식",        "Power Automate 플로우 설계, Excel 보고서, JSON 설정"),
    ("처리 언어",        "한국어(KO) / 영어(EN) / 이중언어(BILINGUAL)"),
]

PREREQUISITES = [
    "Claude Code (claude.com/claude-code) 설치",
    "Microsoft 365 구독 (Power Automate, Excel, Word 이용 시)",
    "인터넷 연결 (AI 모델 호출 필요)",
    "선택) Python 3.8+ (Advanced 모드, Excel 자동화 활용 시)",
]

GETTING_STARTED = [
    "1단계: Claude Code 실행 및 프로젝트 열기",
    "2단계: /consult 명령 또는 업무 자동화 요청 입력",
    "3단계: 요구사항 파싱 (자동화 대상, 현재 도구, 제약사항 확인)",
    "4단계: Quick 또는 Deep 모드 선택 (Quick: 빠름, Deep: 3AI 비교)",
    "5단계: AI 제안안 검토 및 피드백 (재컨설팅 A/B/C)",
    "6단계: 최종 산출물 생성 (Excel 보고서 + Power Automate 플로우 설계 + JSON Blueprint)",
]

FEATURES = [
    {
        "num": "4.1",
        "title": "요구사항 파싱 (parse-requirement)",
        "description": "자유형 업무 요구사항을 구조화. 자동화 대상, 현재 도구, 제약사항, 소요 시간을 추출하고 session_id를 자동 생성합니다.",
        "table_headers": ["추출 항목", "설명", "예시"],
        "table_rows": [
            ("domain", "도메인 분류 (협업/비용/데이터 등)", "협업"),
            ("automation_targets", "자동화할 업무 (2개 이상)", "월간 보고서 취합, 결재 플로우"),
            ("current_tools", "현재 사용 중인 도구", "Excel, Google Sheets, Slack"),
            ("constraints", "제약사항 (보안/API 미지원 등)", "특정 시스템 API 지원 안함"),
        ],
        "warning": None,
    },
    {
        "num": "4.2",
        "title": "AI 3종 의견 비교 (ai-score-compare)",
        "description": "Quick 모드(Claude 단독)와 Deep 모드(Claude+Codex+Gemini 병렬)에서 자유 제안 + 리스크 2패스 평가. 공통 강점/리스크 추출.",
        "table_headers": ["모드", "AI 참여", "처리 시간", "최적 용도"],
        "table_rows": [
            ("Quick", "Claude 단독", "~30초", "빠른 프로토타이핑, 간단한 요구사항"),
            ("Deep", "Claude+Codex+Gemini", "~90초", "정밀 분석, 복잡한 업무 자동화"),
        ],
        "warning": None,
    },
    {
        "num": "4.3",
        "title": "산출물 생성 (generate-output)",
        "description": "최종 권고안을 Excel 보고서, Word 문서, JSON 설정으로 생성. 출력 모드(integrated/user/developer/split) 선택 가능.",
        "table_headers": ["산출물", "형식", "내용"],
        "table_rows": [
            ("Excel 보고서", ".xlsx (KR/EN/BILINGUAL)", "요구사항 요약, 권고안, ROI 예측, 위험도"),
            ("JSON Blueprint", ".json", "Power Automate 플로우 구조 (트리거/액션/분기)"),
            ("텍스트 설계", ".txt", "플로우 다이어그램 + 수동 구현 가이드"),
        ],
        "warning": "Word(.docx) 출력은 STEP 7-E 선택 시 추가 생성됩니다.",
    },
]

DATA_STORAGE_NOTES = [
    "세션 파일: 각 컨설팅마다 logs/session/ 폴더에 JSON 파일로 저장 (session_id 기반)",
    "로그 이력: logs/ai_analysis/, logs/dev/, logs/test/ 폴더에 JSONL 형식으로 누적 기록",
    "산출물: output/ 폴더에 Excel(.xlsx), JSON, 텍스트(.txt) 파일 저장",
    "아카이브: 4주 이상 된 파일은 자동으로 archive/raw/ → archive/cold/ 이동 (2주 후 삭제)",
]

CAUTIONS = [
    "API 제한: Claude API 호출량 제한이 있으므로 Deep 모드 대량 실행 시 주의하세요.",
    "시간대: 복잡한 업무의 경우 Deep 모드에서 ~90초 소요됩니다.",
    "파일명: 한글 OK이나 공백과 특수문자는 언더스코어(_)로 자동 치환됩니다.",
    "Power Automate: Cloud Flow(기본)는 지원, PAD는 향후 지원 예정입니다.",
    "데이터 삭제: 삭제한 세션/로그는 복구되지 않습니다. 중요 파일은 외부 백업을 권장합니다.",
]

FAQS = [
    ("Q. 프로그램이 어떤 MS 제품을 지원하나요?",
     "Excel, Word, Power Automate, Teams, Outlook, SharePoint, OneDrive, Forms, Planner 등 Microsoft 365 핵심 제품을 지원합니다."),
    ("Q. Quick과 Deep 모드의 차이는?",
     "Quick은 Claude 단독으로 ~30초 내 빠른 분석. Deep은 3AI 병렬 ~90초로 정밀 분석합니다."),
    ("Q. Power Automate 플로우를 직접 구현할 수 없으면?",
     "STEP 7-P에서 Copilot 프롬프트와 수동 단계 가이드를 제공합니다."),
    ("Q. 생성된 Excel 보고서를 수정할 수 있나요?",
     "네, 완전한 Word/Excel 파일이므로 자유롭게 수정 가능합니다."),
    ("Q. 재컨설팅은 몇 번까지 가능한가요?",
     "최대 3 사이클(A/B/C 피드백 반복)까지 지원합니다."),
]

# ════════════════════════════════════════════════════════════
# 색상 상수
# ════════════════════════════════════════════════════════════

COLOR_PRIMARY   = RGBColor(0x00, 0x70, 0xC0)
COLOR_SECONDARY = RGBColor(0x00, 0x4E, 0x8A)
COLOR_ACCENT    = RGBColor(0xFF, 0x66, 0x00)
COLOR_GRAY      = RGBColor(0xF2, 0xF2, 0xF2)
COLOR_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)
COLOR_TEXT      = RGBColor(0x1A, 0x1A, 0x1A)
COLOR_ROW_ALT   = RGBColor(0xEA, 0xF4, 0xFF)

# ════════════════════════════════════════════════════════════
# 유틸리티 함수
# ════════════════════════════════════════════════════════════

def set_cell_bg(cell, color):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    hex_color = f"{color[0]:02X}{color[1]:02X}{color[2]:02X}"
    shd.set(qn('w:fill'), hex_color)
    tcPr.append(shd)

def add_rule(doc, color="0070C0"):
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '16')
    bottom.set(qn('w:color'), color)
    pBdr.append(bottom)
    pPr.append(pBdr)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)

def add_section_title(doc, text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(14)
    run.font.bold = True
    run.font.color.rgb = COLOR_PRIMARY
    p.paragraph_format.space_after = Pt(2)
    add_rule(doc)
    doc.add_paragraph()

def add_subsection_title(doc, text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(12)
    run.font.bold = True
    run.font.color.rgb = COLOR_SECONDARY
    p.paragraph_format.space_after = Pt(6)

def add_body_text(doc, text):
    p = doc.add_paragraph(text)
    for run in p.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = COLOR_TEXT
    p.paragraph_format.space_after = Pt(8)

def add_bullet(doc, text):
    p = doc.add_paragraph(text, style='List Bullet')
    for run in p.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = COLOR_TEXT
    p.paragraph_format.space_after = Pt(3)

def add_2col_table(doc, rows_data):
    table = doc.add_table(rows=len(rows_data), cols=2)
    table.style = 'Table Grid'
    for i, (key, val) in enumerate(rows_data):
        row = table.rows[i]
        row.cells[0].text = key
        row.cells[1].text = val
        set_cell_bg(row.cells[0], COLOR_GRAY)
        for cell in row.cells:
            if cell.paragraphs and cell.paragraphs[0].runs:
                cell.paragraphs[0].runs[0].font.size = Pt(9)
    doc.add_paragraph()

def add_feature_table(doc, headers, rows):
    table = doc.add_table(rows=len(rows) + 1, cols=len(headers))
    table.style = 'Table Grid'
    for j, h in enumerate(headers):
        cell = table.rows[0].cells[j]
        cell.text = h
        set_cell_bg(cell, COLOR_PRIMARY)
        if cell.paragraphs and cell.paragraphs[0].runs:
            run = cell.paragraphs[0].runs[0]
            run.font.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = COLOR_WHITE
    for i, row_data in enumerate(rows):
        for j, val in enumerate(row_data):
            cell = table.rows[i + 1].cells[j]
            cell.text = str(val)
            if i % 2 == 0:
                set_cell_bg(cell, COLOR_ROW_ALT)
            if cell.paragraphs and cell.paragraphs[0].runs:
                cell.paragraphs[0].runs[0].font.size = Pt(9)
    doc.add_paragraph()

# ════════════════════════════════════════════════════════════
# 문서 생성
# ════════════════════════════════════════════════════════════

doc = Document()
section = doc.sections[0]
section.top_margin = Cm(2.5)
section.bottom_margin = Cm(2.5)
section.left_margin = Cm(3.0)
section.right_margin = Cm(2.5)

# ── 표지 ──
for _ in range(6):
    doc.add_paragraph()

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run(APP_NAME)
run.font.size = Pt(36)
run.font.bold = True
run.font.color.rgb = COLOR_PRIMARY
p.paragraph_format.space_after = Pt(6)

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run(t("subtitle"))
run.font.size = Pt(20)
run.font.color.rgb = COLOR_SECONDARY
p.paragraph_format.space_after = Pt(4)

add_rule(doc)
doc.add_paragraph()

for label, value in [(t("cover_version"), VERSION), (t("cover_date"), TODAY), (t("cover_audience"), TARGET_AUDIENCE)]:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r1 = p.add_run(f"{label}: ")
    r1.font.size = Pt(11)
    r2 = p.add_run(value)
    r2.font.size = Pt(11)
    r2.font.bold = True
    p.paragraph_format.space_after = Pt(2)

doc.add_page_break()

# ── 목차 ──
p = doc.add_paragraph()
run = p.add_run(t("toc_title"))
run.font.size = Pt(16)
run.font.bold = True
run.font.color.rgb = COLOR_PRIMARY
p.paragraph_format.space_after = Pt(4)
add_rule(doc)
doc.add_paragraph()

toc_items = [
    ("1.", t("sec_overview"), "3"),
    ("2.", t("sec_prerequisites"), "3"),
    ("3.", t("sec_getting_started"), "4"),
    ("4.", t("sec_features"), "5"),
]
for feat in FEATURES:
    toc_items.append((f"  {feat['num']}", feat['title'], "5"))
toc_items.extend([
    ("5.", t("sec_data_storage"), "7"),
    ("6.", t("sec_cautions"), "7"),
    ("7.", t("sec_faq"), "8"),
])

for num, title, page in toc_items:
    p = doc.add_paragraph()
    is_sub = num.startswith("  ")
    p.paragraph_format.left_indent = Cm(0.5) if is_sub else Cm(0)
    r_n = p.add_run(f"{num}  ")
    r_n.font.size = Pt(10)
    r_n.font.bold = not is_sub
    r_t = p.add_run(title)
    r_t.font.size = Pt(10)
    dot_count = max(1, 45 - len(title) - len(num.strip()))
    p.add_run(" " + "." * dot_count + " ").font.size = Pt(10)
    p.add_run(page).font.size = Pt(10)

doc.add_page_break()

# ── 섹션들 ──
add_section_title(doc, f"1.  {t('sec_overview')}")
add_body_text(doc, OVERVIEW_TEXT)
add_2col_table(doc, OVERVIEW_SPECS)

add_section_title(doc, f"2.  {t('sec_prerequisites')}")
for item in PREREQUISITES:
    add_bullet(doc, item)
doc.add_paragraph()

add_section_title(doc, f"3.  {t('sec_getting_started')}")
for item in GETTING_STARTED:
    add_bullet(doc, item)
doc.add_paragraph()

add_section_title(doc, f"4.  {t('sec_features')}")
for feat in FEATURES:
    add_subsection_title(doc, f"{feat['num']}  {feat['title']}")
    add_body_text(doc, feat["description"])
    if feat.get("table_headers") and feat.get("table_rows"):
        add_feature_table(doc, feat["table_headers"], feat["table_rows"])

doc.add_page_break()
add_section_title(doc, f"5.  {t('sec_data_storage')}")
for item in DATA_STORAGE_NOTES:
    add_bullet(doc, item)
doc.add_paragraph()

add_section_title(doc, f"6.  {t('sec_cautions')}")
for item in CAUTIONS:
    add_bullet(doc, item)
doc.add_paragraph()

doc.add_page_break()
add_section_title(doc, f"7.  {t('sec_faq')}")
for q, a in FAQS:
    p = doc.add_paragraph()
    run = p.add_run(q)
    run.font.size = Pt(10)
    run.font.bold = True
    run.font.color.rgb = COLOR_SECONDARY
    p.paragraph_format.space_after = Pt(2)

    p = doc.add_paragraph()
    run = p.add_run(a)
    run.font.size = Pt(10)
    run.font.color.rgb = COLOR_TEXT
    p.paragraph_format.left_indent = Cm(0.5)
    p.paragraph_format.space_after = Pt(10)

# ── 저장 ──
os.makedirs(os.path.dirname(OUTPUT_PATH) or ".", exist_ok=True)
doc.save(OUTPUT_PATH)
print(f"[완료] 매뉴얼이 생성되었습니다: {OUTPUT_PATH}")
